#-----------------------
# AutoCommand 設定ファイル
#-----------------------
#
# 実行するコマンドを増やす際は 「 - コマンド名」 と書き足してください
##############################################################


# サーバーを起動した際に実行するコマンドをここで指定します
# 以下使用例に沿った書き方をしてください。

# 起動時:
#  - time set 0
#  - time stop

起動時:



##############################################################


# サーバーを起動した際に遅延を挟んで実行するコマンドをここで指定します
# 遅延の単位は秒です。下記例の場合60秒ということになります
# 以下使用例に沿った書き方をしてください。
# sをつけ忘れないようにしてください

# 遅延:
#  60s:
#   - whitelist on
#   - whitelist reload

遅延:



##############################################################


# プレイヤーが特定人数参加した際に実行するコマンドをここで指定します
# 下記例の場合5人参加したら実行するということになります
# 以下使用例に沿った書き方をしてください。
# pをつけ忘れないようにしてください

# 参加人数:
#  1p:
#   - say あなたが最初の参加者です
#  10p:
#   - say 鯖開始から10人目が参加しました

参加人数:


